"""empty message

Revision ID: 27b79b1e7d1e
Revises: 2f91c9233e50
Create Date: 2024-09-18 16:12:02.248273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b79b1e7d1e'
down_revision = '2f91c9233e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mozoCaller', schema=None) as batch_op:
        batch_op.create_index('idx_mesa_cuenta_cobrado', ['id_mesa', 'cuenta', 'cobrado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mozoCaller', schema=None) as batch_op:
        batch_op.drop_index('idx_mesa_cuenta_cobrado')

    # ### end Alembic commands ###
