"""empty message

Revision ID: 2f91c9233e50
Revises: 6998b14f6c72
Create Date: 2024-09-17 21:03:44.758188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f91c9233e50'
down_revision = '6998b14f6c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mozoCaller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cobrado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mozoCaller', schema=None) as batch_op:
        batch_op.drop_column('cobrado')
        batch_op.drop_column('cuenta')

    # ### end Alembic commands ###
