"""Agregar tablas de ususarios y permisos

Revision ID: 5cfd3121546f
Revises: ff11ab5dd812
Create Date: 2024-09-05 16:18:57.248812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfd3121546f'
down_revision = 'ff11ab5dd812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('permisos')
    # ### end Alembic commands ###
