"""Agregar tablas de imágenes y ajustes de modelo

Revision ID: ff11ab5dd812
Revises: e1bec671c65c
Create Date: 2024-09-04 15:18:48.368914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff11ab5dd812'
down_revision = 'e1bec671c65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_menu', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_menu'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen')
    # ### end Alembic commands ###
